apiVersion: v1
kind: Pod
metadata:
  labels:
    run: server
  name: server
spec:
  volumes:
  - name: dir
    hostPath: 
      path: /root/allure-report
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: server
    volumeMounts:
    - name: dir
      mountPath: /usr/share/nginx/html
  restartPolicy: Never
