# used by TestOne.testOne_two
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
       - name: web
         hostPath:
           type: Directory
           path: /web
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
         - mountPath: /usr/share/nginx/html
           name: web
