name: Java CI with Gradle

on:
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: UI and API Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: always()
    
    - name: login to container registry
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: start json container
      run: >-
        docker run -d --rm -p 81:80  -e "DB=users.json" 
        -v ${{ github.workspace }}/json-server:/data ghcr.io/amado-saladino/json-server:v1
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: test workspace
      run: echo ${{ github.workspace }}
      
    - name: call json server
      run: curl localhost:81/users
        
    - name: test with gradle
      run: gradle clean test
        
    - name: Test Report
      if: always()
      uses: ScaCap/action-surefire-report@v1.0.5
      with:
        check_name: Test Summary Report
        github_token: ${{ github.token }}
        report_paths: "build/test-results/test/TEST-*.xml"
        
    - name: JUnit Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Test Report
        path: build/test-results/test/TEST-*.xml
        reporter: java-junit
        fail-on-error: 'false'
        
    - name: HTML Test Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: "build/reports/tests/test/*"

    - name: Allure report files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: "allure-results"
        
    - name: Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 5
        
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        
    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test allure report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: amado-saladino.github.io/supernova

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: "screenshots/*" 
